apiVersion: v1
kind: ServiceAccount
metadata:
  name: terminal-pod
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: terminal-pod
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: terminal-pod
subjects:
- kind: ServiceAccount
  name: terminal-pod
  namespace: default
roleRef:
  kind: ClusterRole
  name: terminal-pod
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: terminal-pod
spec:
  serviceAccountName: terminal-pod
  containers:
    - name: terminal-container
      image: ubuntu:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 3600; done"]  # Keep the container running
      env:
        - name: MONGO_HOST
          value: http://localhost  # Replace with the host and port of your MongoDB instance
        - name: MONGO_PORT
          value: "27017"   # Replace with the port of your MongoDB instance
