apiVersion: v1
kind: Pod
metadata:
  name: terminal-pod
spec:
  containers:
    - name: terminal-container
      image: ubuntu:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 3600; done"]  # Keep the container running
      env:
        - name: MONGO_HOST
          value: http://localhost  # Replace with the host and port of your MongoDB instance
        - name: MONGO_PORT
          value: "27017"   # Replace with the port of your MongoDB instance
